/**
 * @internal
 */
export enum ErrorType {
	NO_EMPTY_KEYNAME = 101,
	KEYNAME_TOO_LARGE,
	DATA_NOT_ALLOWED_IN_DATASTORE,
	CANNOT_STORE_DATA_IN_DATASTORE,
	VALUE_TOO_LARGE,
	MAX_VAL_AND_MIN_VAL_NOT_INTEGERS,
	PAGE_SIZE_MUST_BE_IN_RANGE /* =106 */,
	NO_API_ACCESS_ALLOWED,
	ORDERERD_DATATORE_DELETED,
	CANNOT_PARSE_RESPONSE,
	API_SERVICES_REJECTED,
	KEY_NOT_FOUND,
	MALFORMED_DATASTORE_RESPONSE,
	MALFORMED_ORDERED_DATASTORE_RESPONSE,
	METADATA_TOO_LARGE,
	USERID_LIMIT_TOO_LARGE,
	USERID_ATTRIBUTE_INVALID,
	METATADA_ATTRIBUTE_INVALID,
}
