import robloxUrlConstructor, { RobloxEnvironmentType, RobloxPlatformType } from './lib/roblox_url_constructor';

console.log(
  robloxUrlConstructor.constructServiceUrl(
    RobloxPlatformType.BEDEV1,
    'users',
    'hi/{{babe}}/',
    false,
    true,
    false,
    {},
    'momma',
  ),
);
console.log(
  robloxUrlConstructor.constructServiceUrl(
    RobloxPlatformType.BEDEV2,
    'captcha',
    '/v1/{{provider}}/metadata/{{captchaId}}/rblx-dev-2',
    false,
    false,
    false,
    {},
    'arkoselabs',
  ),
);
console.log(
  robloxUrlConstructor.constructServiceUrlByEnvironment(
    RobloxPlatformType.BEDEV2,
    'captcha',
    RobloxEnvironmentType.Development,
    '/v1/{{provider}}/metadata/{{captchaId}}/rblx-dev-2',
    false,
    false,
    false,
    {},
    'arkoselabs',
  ),
);
console.log(
  robloxUrlConstructor.smartConstruct(
    '{bedev1:users:v1:sitetest1.simulpong.com:true}/test/{{userId}}/{{otherArg}}',
    {},
    123,
    'foo',
  ),
);
console.log(robloxUrlConstructor.smartConstruct('{bedev2:develop:v1:simulpong.com}/help-me', { randomQuery: 'foo' }));
